name: CI checks

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test on ${{ matrix.os }} with ${{ matrix.feature_set }} features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        feature_set: [basic, all]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - feature_set: basic
            features: batch,dev-graph,gadget-traces
          - feature_set: all
            features: batch,dev-graph,gadget-traces,test-dev-graph,thread-safe-region,sanity-checks,circuit-params

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --release --workspace --no-default-features --features "${{ matrix.features }}"

  examples:
    name: Run the examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
      # - name: Get example targets and features
      #   id: get-examples
      #   run: |
      #     # Get the list of examples from "examples" dir & Cargo.toml
      #     EXAMPLES_WITH_FEATURES=$(awk '/^\[\[example\]\]/ { getline; name=$3; name=substr(name, 2, length(name)-2); getline; if ($1 == "required-features") { features=$NF; gsub(/["\[\]]/, "", features); print name "#" features } }' ./halo2_proofs/Cargo.toml)
      #     EXAMPLES_WITHOUT_FEATURES=$(ls ./halo2_proofs/examples/*.rs | xargs -n1 basename -s .rs)
          
      #     # Remove examples with features listed in Cargo.toml from examples without features
      #     EXAMPLES_WITHOUT_FEATURES=$(echo "$EXAMPLES_WITHOUT_FEATURES" | grep -vFx "$(echo "$EXAMPLES_WITH_FEATURES" | cut -d '#' -f 1)")

      #     # Combine examples with and without features
      #     EXAMPLES=$(echo "$EXAMPLES_WITH_FEATURES $EXAMPLES_WITHOUT_FEATURES" | tr ' ' '\n' | sort -u | tr '\n' ' ')
          
      #     echo "::set-output name=examples::$EXAMPLES"

      # - name: Run examples
      #   run: |
      #     for example in ${{ steps.get-examples.outputs.examples }}; do
      #       if [[ "$example" == *"#"* ]]; then
      #         name=$(echo $example | cut -d '#' -f 1)
      #         features=$(echo $example | cut -d '#' -f 2)
      #         cargo run --package halo2_proofs --example $name --features $features
      #       else
      #         cargo run --package halo2_proofs --example $example
      #       fi
      #     done
      - name: Run examples
        run: |
          .github/scripts/run-examples.sh

  build:
    name: Build target ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown
          - wasm32-wasi

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
          default: true
      - name: Add target
        run: rustup target add ${{ matrix.target }}
      - name: Run script file
        run: |
          .github/scripts/wasm-target-test-build.sh

  bitrot:
    name: Bitrot check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      # Build benchmarks to prevent bitrot
      - name: Build benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --benches --examples --all-features

  doc-links:
    name: Intra-doc links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: cargo fetch
        uses: actions-rs/cargo@v1
        with:
          command: fetch

      # Ensure intra-documentation links all resolve correctly
      # Requires #![deny(intra_doc_link_resolution_failure)] in crates.
      - name: Check intra-doc links
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --document-private-items

  fmt:
    name: Rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

